title: tessmero.github.io
description: tessmero.github.io


# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag  



collections:
  demos:
    output: true
    permalink: /:name
  changelogs:
    output: false
  techs:
    output: false

# checked by bash scripts after jekyll build
# replace index.html with existing page
homepage: tremolo.html

# demos to include in navigation bar
header_pages:
  - "_demos/ski-stunt.md"
  - "_demos/orbital-launch.md"
  - "_demos/collide-o-scope.md"
  - "_demos/sketch-ball.md"
         
  


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
