title: tessmero.github.io
description: tessmero.github.io


# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag  



collections:
  demos:
    output: true
    permalink: /:name
  changelogs:
    output: true
  techs:
    output: true

# navigation bar with dropdowns
header_pages:
  - "_demos/boating-school.md"
  - "_demos/collide-o-scope.md"
  - "_demos/orbital-launch.md"
  - "_demos/warp.md"
         
  


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
